linters:
  Indentation:
    width: 1
    character: tab

  LeadingZero:
    enabled: true
    style: include_zero

  NestingDepth:
    max_depth: 5

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: false

  SelectorFormat:
    convention: classic_BEM

